- hosts: masters
  roles:
   - role: elastic.elasticsearch
  vars:
   es_heap_size: "16g"
   es_data_dirs:
      - "/es-data/elasticsearch"
   es_config:
     cluster.name: "ENTER CLUSTER NAME HERE"
     network.host: 0
     cluster.initial_master_nodes: "ENTER IPs OF ALL MASTER NODES HERE SEPARATED BY COMMAS"
     discovery.seed_hosts: "ANY ONE MASTER NODE HERE (ref a)"
     http.port: 9200
     node.data: true
     node.master: true
     node.ingest: true
     node.ml: true
     cluster.remote.connect: false
     bootstrap.memory_lock: true
- hosts: data
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/es-data/elasticsearch"
    es_heap_size: "16g"
    es_config:
      cluster.name: "ENTER CLUSTER NAME HERE"
      network.host: 0
      discovery.seed_hosts: "(a - ENTER SAME MASTER NODE (one number) MENTIONED ABOVE)"
      http.port: 9200
      node.data: true
      node.master: false
      node.ml: false
      bootstrap.memory_lock: true
      indices.recovery.max_bytes_per_sec: 100mb
- hosts: coordinating
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "16g"
    es_config:
      cluster.name: "ENTER CLUSTER NAME HERE"
      network.host: 0
      discovery.seed_hosts: "(a - ENTER SAME MASTER NODE (one number) MENTIONED ABOVE)"
      http.port: 9200
      node.data: false
      node.master: false
      node.ingest: false
      node.ml: false
      bootstrap.memory_lock: true
