- hosts: kibana
  gather_facts: yes
  become: yes
  roles:
          - role: jdauphant.nginx
            nginx_events_params:
                    - worker_connections 2000
                    - multi_accept on
                    - use epoll
            nginx_http_params:
                    - sendfile "on"
                    - tcp_nodelay "on"
            nginx_worker_processes: 8
            nginx_worker_rlimit_nofile: 40000
            vars:
                    - my_extra_params:
                            - client_max_body_size 1000M
            nginx_sites:
                    kibana:
                            - listen 5600
                            - |
                                    location / {
                                            proxy_pass http://localhost:5601/;
                                            }
                            - |

- hosts: coordinating
  gather_facts: yes
  become: yes
  roles:
          - role: jdauphant.nginx
            nginx_events_params:
                    - worker_connections 2000
                    - multi_accept on
                    - use epoll
            nginx_http_params:
                    - sendfile "on"
                    - tcp_nodelay "on"
            nginx_worker_processes: 8
            nginx_worker_rlimit_nofile: 40000
            vars:
                    - my_extra_params:
                            - client_max_body_size 1000M
            nginx_sites:
                    es:
                            - listen 9201
                            - |
                                    location / {
                                            proxy_pass http://localhost:9200/;
                                            }
                            - |
